<Project>
	<Target Name="EmbedDependencies" Condition="$(EmbedDependencyList) == 'true'" AfterTargets="AfterResolveReferences">
		<ItemGroup>
			<EmbeddedResource Include="@(ReferenceCopyLocalPaths)"
				Condition="'$(DependencyEmbeds.Contains(%(Filename)))' == 'true' And '%(Extension)' == '.dll'" />
		</ItemGroup>
	</Target>
	<Target Name="CleanupOutput" Condition="$(CleanupBuildOutput) == 'true'" AfterTargets="Build">
		<ItemGroup>
			<FilesToDelete Include="$(OutputPath)*.*" 
				Exclude="$(OutputPath)$(AssemblyName).dll;$(OutputPath)$(AssemblyName).pdb" />
		</ItemGroup>
		<Delete Files="@(FilesToDelete)" />
	</Target>
	<Target Name="RunAfterBuild" AfterTargets="Build">
		<MSBuild Projects="@(RunAfterBuild)" Targets="Build" Properties="Configuration=$(Configuration)" />
		<Exec 
			Command="dotnet &quot;%(RunAfterBuild.RootDir)%(RunAfterBuild.Directory)bin/$(Configuration)/net10.0/%(RunAfterBuild.Filename).dll&quot; &quot;$(TargetPath)&quot;" />
	</Target>
</Project>