//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/SrDslParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISrDslParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class SrDslParserBaseListener : ISrDslParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.root"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRoot([NotNull] SrDslParser.RootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.root"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRoot([NotNull] SrDslParser.RootContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.split_order"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSplit_order([NotNull] SrDslParser.Split_orderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.split_order"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSplit_order([NotNull] SrDslParser.Split_orderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.splitdef_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSplitdef_node([NotNull] SrDslParser.Splitdef_nodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.splitdef_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSplitdef_node([NotNull] SrDslParser.Splitdef_nodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.runimmediate_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRunimmediate_node([NotNull] SrDslParser.Runimmediate_nodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.runimmediate_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRunimmediate_node([NotNull] SrDslParser.Runimmediate_nodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.any_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAny_node([NotNull] SrDslParser.Any_nodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.any_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAny_node([NotNull] SrDslParser.Any_nodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.all_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAll_node([NotNull] SrDslParser.All_nodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.all_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAll_node([NotNull] SrDslParser.All_nodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.gcn_opt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGcn_opt([NotNull] SrDslParser.Gcn_optContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.gcn_opt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGcn_opt([NotNull] SrDslParser.Gcn_optContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.gcn_nonopt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGcn_nonopt([NotNull] SrDslParser.Gcn_nonoptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.gcn_nonopt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGcn_nonopt([NotNull] SrDslParser.Gcn_nonoptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.grouped_condition_node_opt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGrouped_condition_node_opt([NotNull] SrDslParser.Grouped_condition_node_optContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.grouped_condition_node_opt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGrouped_condition_node_opt([NotNull] SrDslParser.Grouped_condition_node_optContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.grouped_condition_node_nonopt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGrouped_condition_node_nonopt([NotNull] SrDslParser.Grouped_condition_node_nonoptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.grouped_condition_node_nonopt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGrouped_condition_node_nonopt([NotNull] SrDslParser.Grouped_condition_node_nonoptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.grouped_condition_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGrouped_condition_node([NotNull] SrDslParser.Grouped_condition_nodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.grouped_condition_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGrouped_condition_node([NotNull] SrDslParser.Grouped_condition_nodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.condition_node_opt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition_node_opt([NotNull] SrDslParser.Condition_node_optContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.condition_node_opt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition_node_opt([NotNull] SrDslParser.Condition_node_optContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.condition_node_nonopt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition_node_nonopt([NotNull] SrDslParser.Condition_node_nonoptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.condition_node_nonopt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition_node_nonopt([NotNull] SrDslParser.Condition_node_nonoptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.nongrouped_condition_node_opt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNongrouped_condition_node_opt([NotNull] SrDslParser.Nongrouped_condition_node_optContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.nongrouped_condition_node_opt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNongrouped_condition_node_opt([NotNull] SrDslParser.Nongrouped_condition_node_optContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.nongrouped_condition_node_nonopt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNongrouped_condition_node_nonopt([NotNull] SrDslParser.Nongrouped_condition_node_nonoptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.nongrouped_condition_node_nonopt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNongrouped_condition_node_nonopt([NotNull] SrDslParser.Nongrouped_condition_node_nonoptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.nongrouped_condition_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNongrouped_condition_node([NotNull] SrDslParser.Nongrouped_condition_nodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.nongrouped_condition_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNongrouped_condition_node([NotNull] SrDslParser.Nongrouped_condition_nodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.split_logic_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSplit_logic_node([NotNull] SrDslParser.Split_logic_nodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.split_logic_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSplit_logic_node([NotNull] SrDslParser.Split_logic_nodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.logic_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogic_node([NotNull] SrDslParser.Logic_nodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.logic_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogic_node([NotNull] SrDslParser.Logic_nodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.call_arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall_arg([NotNull] SrDslParser.Call_argContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.call_arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall_arg([NotNull] SrDslParser.Call_argContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.call_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall_node([NotNull] SrDslParser.Call_nodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.call_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall_node([NotNull] SrDslParser.Call_nodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.call_shorthand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall_shorthand([NotNull] SrDslParser.Call_shorthandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.call_shorthand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall_shorthand([NotNull] SrDslParser.Call_shorthandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.comparison_binaryrh_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison_binaryrh_node([NotNull] SrDslParser.Comparison_binaryrh_nodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.comparison_binaryrh_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison_binaryrh_node([NotNull] SrDslParser.Comparison_binaryrh_nodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.binary_lh_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinary_lh_node([NotNull] SrDslParser.Binary_lh_nodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.binary_lh_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinary_lh_node([NotNull] SrDslParser.Binary_lh_nodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.comparison_full"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison_full([NotNull] SrDslParser.Comparison_fullContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.comparison_full"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison_full([NotNull] SrDslParser.Comparison_fullContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.comparison_shorthand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison_shorthand([NotNull] SrDslParser.Comparison_shorthandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.comparison_shorthand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison_shorthand([NotNull] SrDslParser.Comparison_shorthandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.comparison_l"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison_l([NotNull] SrDslParser.Comparison_lContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.comparison_l"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison_l([NotNull] SrDslParser.Comparison_lContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.comparison_andor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison_andor([NotNull] SrDslParser.Comparison_andorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.comparison_andor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison_andor([NotNull] SrDslParser.Comparison_andorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison([NotNull] SrDslParser.ComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison([NotNull] SrDslParser.ComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.binary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinary([NotNull] SrDslParser.BinaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.binary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinary([NotNull] SrDslParser.BinaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.if_branch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_branch([NotNull] SrDslParser.If_branchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.if_branch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_branch([NotNull] SrDslParser.If_branchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_statement([NotNull] SrDslParser.If_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_statement([NotNull] SrDslParser.If_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.else_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_statement([NotNull] SrDslParser.Else_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.else_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_statement([NotNull] SrDslParser.Else_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.else_if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_if_statement([NotNull] SrDslParser.Else_if_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.else_if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_if_statement([NotNull] SrDslParser.Else_if_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.timer_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTimer_node([NotNull] SrDslParser.Timer_nodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.timer_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTimer_node([NotNull] SrDslParser.Timer_nodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.event_listen_group"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEvent_listen_group([NotNull] SrDslParser.Event_listen_groupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.event_listen_group"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEvent_listen_group([NotNull] SrDslParser.Event_listen_groupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.event_listen"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEvent_listen([NotNull] SrDslParser.Event_listenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.event_listen"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEvent_listen([NotNull] SrDslParser.Event_listenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.bounds_grouped"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBounds_grouped([NotNull] SrDslParser.Bounds_groupedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.bounds_grouped"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBounds_grouped([NotNull] SrDslParser.Bounds_groupedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.bounds_object_grouped"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBounds_object_grouped([NotNull] SrDslParser.Bounds_object_groupedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.bounds_object_grouped"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBounds_object_grouped([NotNull] SrDslParser.Bounds_object_groupedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.bounds_object_size_grouped"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBounds_object_size_grouped([NotNull] SrDslParser.Bounds_object_size_groupedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.bounds_object_size_grouped"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBounds_object_size_grouped([NotNull] SrDslParser.Bounds_object_size_groupedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.bounds_condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBounds_condition([NotNull] SrDslParser.Bounds_conditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.bounds_condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBounds_condition([NotNull] SrDslParser.Bounds_conditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.bounds_object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBounds_object([NotNull] SrDslParser.Bounds_objectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.bounds_object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBounds_object([NotNull] SrDslParser.Bounds_objectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.bounds_object_size"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBounds_object_size([NotNull] SrDslParser.Bounds_object_sizeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.bounds_object_size"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBounds_object_size([NotNull] SrDslParser.Bounds_object_sizeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.property_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_access([NotNull] SrDslParser.Property_accessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.property_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_access([NotNull] SrDslParser.Property_accessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.object_condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject_condition([NotNull] SrDslParser.Object_conditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.object_condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject_condition([NotNull] SrDslParser.Object_conditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.object_condition_component"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject_condition_component([NotNull] SrDslParser.Object_condition_componentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.object_condition_component"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject_condition_component([NotNull] SrDslParser.Object_condition_componentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.datatype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatatype([NotNull] SrDslParser.DatatypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.datatype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatatype([NotNull] SrDslParser.DatatypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] SrDslParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] SrDslParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.bool_dt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_dt([NotNull] SrDslParser.Bool_dtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.bool_dt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_dt([NotNull] SrDslParser.Bool_dtContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
