//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/SrDslParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SrDslParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ISrDslParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoot([NotNull] SrDslParser.RootContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.split_order"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSplit_order([NotNull] SrDslParser.Split_orderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.splitdef_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSplitdef_node([NotNull] SrDslParser.Splitdef_nodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.runimmediate_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRunimmediate_node([NotNull] SrDslParser.Runimmediate_nodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.any_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAny_node([NotNull] SrDslParser.Any_nodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.all_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAll_node([NotNull] SrDslParser.All_nodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.gcn_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGcn_opt([NotNull] SrDslParser.Gcn_optContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.gcn_nonopt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGcn_nonopt([NotNull] SrDslParser.Gcn_nonoptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.grouped_condition_node_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrouped_condition_node_opt([NotNull] SrDslParser.Grouped_condition_node_optContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.grouped_condition_node_nonopt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrouped_condition_node_nonopt([NotNull] SrDslParser.Grouped_condition_node_nonoptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.grouped_condition_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrouped_condition_node([NotNull] SrDslParser.Grouped_condition_nodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.condition_node_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition_node_opt([NotNull] SrDslParser.Condition_node_optContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.condition_node_nonopt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition_node_nonopt([NotNull] SrDslParser.Condition_node_nonoptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.nongrouped_condition_node_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNongrouped_condition_node_opt([NotNull] SrDslParser.Nongrouped_condition_node_optContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.nongrouped_condition_node_nonopt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNongrouped_condition_node_nonopt([NotNull] SrDslParser.Nongrouped_condition_node_nonoptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.nongrouped_condition_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNongrouped_condition_node([NotNull] SrDslParser.Nongrouped_condition_nodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.split_logic_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSplit_logic_node([NotNull] SrDslParser.Split_logic_nodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.logic_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogic_node([NotNull] SrDslParser.Logic_nodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.call_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall_arg([NotNull] SrDslParser.Call_argContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.call_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall_node([NotNull] SrDslParser.Call_nodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.call_shorthand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall_shorthand([NotNull] SrDslParser.Call_shorthandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.comparison_binaryrh_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison_binaryrh_node([NotNull] SrDslParser.Comparison_binaryrh_nodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.binary_lh_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_lh_node([NotNull] SrDslParser.Binary_lh_nodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.comparison_full"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison_full([NotNull] SrDslParser.Comparison_fullContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.comparison_shorthand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison_shorthand([NotNull] SrDslParser.Comparison_shorthandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.comparison_l"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison_l([NotNull] SrDslParser.Comparison_lContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.comparison_andor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison_andor([NotNull] SrDslParser.Comparison_andorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison([NotNull] SrDslParser.ComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary([NotNull] SrDslParser.BinaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.if_branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_branch([NotNull] SrDslParser.If_branchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] SrDslParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.else_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_statement([NotNull] SrDslParser.Else_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.else_if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_if_statement([NotNull] SrDslParser.Else_if_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.timer_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimer_node([NotNull] SrDslParser.Timer_nodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.event_listen_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEvent_listen_group([NotNull] SrDslParser.Event_listen_groupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.event_listen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEvent_listen([NotNull] SrDslParser.Event_listenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.bounds_grouped"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBounds_grouped([NotNull] SrDslParser.Bounds_groupedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.bounds_object_grouped"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBounds_object_grouped([NotNull] SrDslParser.Bounds_object_groupedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.bounds_object_size_grouped"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBounds_object_size_grouped([NotNull] SrDslParser.Bounds_object_size_groupedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.bounds_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBounds_condition([NotNull] SrDslParser.Bounds_conditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.bounds_object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBounds_object([NotNull] SrDslParser.Bounds_objectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.bounds_object_size"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBounds_object_size([NotNull] SrDslParser.Bounds_object_sizeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.property_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProperty_access([NotNull] SrDslParser.Property_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.object_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_condition([NotNull] SrDslParser.Object_conditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.object_condition_component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_condition_component([NotNull] SrDslParser.Object_condition_componentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.datatype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatatype([NotNull] SrDslParser.DatatypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] SrDslParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SrDslParser.bool_dt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_dt([NotNull] SrDslParser.Bool_dtContext context);
}
