//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/SrDslParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SrDslParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ISrDslParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRoot([NotNull] SrDslParser.RootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRoot([NotNull] SrDslParser.RootContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.split_order"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSplit_order([NotNull] SrDslParser.Split_orderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.split_order"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSplit_order([NotNull] SrDslParser.Split_orderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.splitdef_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSplitdef_node([NotNull] SrDslParser.Splitdef_nodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.splitdef_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSplitdef_node([NotNull] SrDslParser.Splitdef_nodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.runimmediate_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRunimmediate_node([NotNull] SrDslParser.Runimmediate_nodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.runimmediate_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRunimmediate_node([NotNull] SrDslParser.Runimmediate_nodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.any_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAny_node([NotNull] SrDslParser.Any_nodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.any_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAny_node([NotNull] SrDslParser.Any_nodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.all_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAll_node([NotNull] SrDslParser.All_nodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.all_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAll_node([NotNull] SrDslParser.All_nodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.gcn_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGcn_opt([NotNull] SrDslParser.Gcn_optContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.gcn_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGcn_opt([NotNull] SrDslParser.Gcn_optContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.gcn_nonopt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGcn_nonopt([NotNull] SrDslParser.Gcn_nonoptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.gcn_nonopt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGcn_nonopt([NotNull] SrDslParser.Gcn_nonoptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.grouped_condition_node_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGrouped_condition_node_opt([NotNull] SrDslParser.Grouped_condition_node_optContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.grouped_condition_node_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGrouped_condition_node_opt([NotNull] SrDslParser.Grouped_condition_node_optContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.grouped_condition_node_nonopt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGrouped_condition_node_nonopt([NotNull] SrDslParser.Grouped_condition_node_nonoptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.grouped_condition_node_nonopt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGrouped_condition_node_nonopt([NotNull] SrDslParser.Grouped_condition_node_nonoptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.grouped_condition_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGrouped_condition_node([NotNull] SrDslParser.Grouped_condition_nodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.grouped_condition_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGrouped_condition_node([NotNull] SrDslParser.Grouped_condition_nodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.condition_node_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition_node_opt([NotNull] SrDslParser.Condition_node_optContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.condition_node_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition_node_opt([NotNull] SrDslParser.Condition_node_optContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.condition_node_nonopt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition_node_nonopt([NotNull] SrDslParser.Condition_node_nonoptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.condition_node_nonopt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition_node_nonopt([NotNull] SrDslParser.Condition_node_nonoptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.nongrouped_condition_node_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNongrouped_condition_node_opt([NotNull] SrDslParser.Nongrouped_condition_node_optContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.nongrouped_condition_node_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNongrouped_condition_node_opt([NotNull] SrDslParser.Nongrouped_condition_node_optContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.nongrouped_condition_node_nonopt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNongrouped_condition_node_nonopt([NotNull] SrDslParser.Nongrouped_condition_node_nonoptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.nongrouped_condition_node_nonopt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNongrouped_condition_node_nonopt([NotNull] SrDslParser.Nongrouped_condition_node_nonoptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.nongrouped_condition_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNongrouped_condition_node([NotNull] SrDslParser.Nongrouped_condition_nodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.nongrouped_condition_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNongrouped_condition_node([NotNull] SrDslParser.Nongrouped_condition_nodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.split_logic_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSplit_logic_node([NotNull] SrDslParser.Split_logic_nodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.split_logic_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSplit_logic_node([NotNull] SrDslParser.Split_logic_nodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.logic_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogic_node([NotNull] SrDslParser.Logic_nodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.logic_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogic_node([NotNull] SrDslParser.Logic_nodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.call_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall_arg([NotNull] SrDslParser.Call_argContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.call_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall_arg([NotNull] SrDslParser.Call_argContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.call_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall_node([NotNull] SrDslParser.Call_nodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.call_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall_node([NotNull] SrDslParser.Call_nodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.call_shorthand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall_shorthand([NotNull] SrDslParser.Call_shorthandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.call_shorthand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall_shorthand([NotNull] SrDslParser.Call_shorthandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.comparison_binaryrh_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison_binaryrh_node([NotNull] SrDslParser.Comparison_binaryrh_nodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.comparison_binaryrh_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison_binaryrh_node([NotNull] SrDslParser.Comparison_binaryrh_nodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.binary_lh_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinary_lh_node([NotNull] SrDslParser.Binary_lh_nodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.binary_lh_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinary_lh_node([NotNull] SrDslParser.Binary_lh_nodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.comparison_full"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison_full([NotNull] SrDslParser.Comparison_fullContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.comparison_full"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison_full([NotNull] SrDslParser.Comparison_fullContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.comparison_shorthand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison_shorthand([NotNull] SrDslParser.Comparison_shorthandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.comparison_shorthand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison_shorthand([NotNull] SrDslParser.Comparison_shorthandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.comparison_l"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison_l([NotNull] SrDslParser.Comparison_lContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.comparison_l"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison_l([NotNull] SrDslParser.Comparison_lContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.comparison_andor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison_andor([NotNull] SrDslParser.Comparison_andorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.comparison_andor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison_andor([NotNull] SrDslParser.Comparison_andorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison([NotNull] SrDslParser.ComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison([NotNull] SrDslParser.ComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinary([NotNull] SrDslParser.BinaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinary([NotNull] SrDslParser.BinaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.if_branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_branch([NotNull] SrDslParser.If_branchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.if_branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_branch([NotNull] SrDslParser.If_branchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_statement([NotNull] SrDslParser.If_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_statement([NotNull] SrDslParser.If_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.else_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_statement([NotNull] SrDslParser.Else_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.else_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_statement([NotNull] SrDslParser.Else_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.else_if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_if_statement([NotNull] SrDslParser.Else_if_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.else_if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_if_statement([NotNull] SrDslParser.Else_if_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.timer_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTimer_node([NotNull] SrDslParser.Timer_nodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.timer_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTimer_node([NotNull] SrDslParser.Timer_nodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.event_listen_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEvent_listen_group([NotNull] SrDslParser.Event_listen_groupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.event_listen_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEvent_listen_group([NotNull] SrDslParser.Event_listen_groupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.event_listen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEvent_listen([NotNull] SrDslParser.Event_listenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.event_listen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEvent_listen([NotNull] SrDslParser.Event_listenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.bounds_grouped"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBounds_grouped([NotNull] SrDslParser.Bounds_groupedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.bounds_grouped"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBounds_grouped([NotNull] SrDslParser.Bounds_groupedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.bounds_object_grouped"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBounds_object_grouped([NotNull] SrDslParser.Bounds_object_groupedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.bounds_object_grouped"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBounds_object_grouped([NotNull] SrDslParser.Bounds_object_groupedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.bounds_object_size_grouped"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBounds_object_size_grouped([NotNull] SrDslParser.Bounds_object_size_groupedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.bounds_object_size_grouped"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBounds_object_size_grouped([NotNull] SrDslParser.Bounds_object_size_groupedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.bounds_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBounds_condition([NotNull] SrDslParser.Bounds_conditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.bounds_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBounds_condition([NotNull] SrDslParser.Bounds_conditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.bounds_object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBounds_object([NotNull] SrDslParser.Bounds_objectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.bounds_object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBounds_object([NotNull] SrDslParser.Bounds_objectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.bounds_object_size"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBounds_object_size([NotNull] SrDslParser.Bounds_object_sizeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.bounds_object_size"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBounds_object_size([NotNull] SrDslParser.Bounds_object_sizeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.property_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_access([NotNull] SrDslParser.Property_accessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.property_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_access([NotNull] SrDslParser.Property_accessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.object_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject_condition([NotNull] SrDslParser.Object_conditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.object_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject_condition([NotNull] SrDslParser.Object_conditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.object_condition_component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject_condition_component([NotNull] SrDslParser.Object_condition_componentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.object_condition_component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject_condition_component([NotNull] SrDslParser.Object_condition_componentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.datatype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatatype([NotNull] SrDslParser.DatatypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.datatype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatatype([NotNull] SrDslParser.DatatypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] SrDslParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] SrDslParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SrDslParser.bool_dt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool_dt([NotNull] SrDslParser.Bool_dtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SrDslParser.bool_dt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool_dt([NotNull] SrDslParser.Bool_dtContext context);
}
